dependencies:
  - python=3.5.4
  - scikit-learn
  - scikit-image
  - scipy
  - pandas
  - numpy
  - matplotlib
  - jupyter
  - spyder
  - tensorflow
  - pip
  - parso=0.7
  - pip:
    - treelib
    - pathos
